version: 0.2

phases:
  install:
    commands:
      - echo "building the project"
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm build run && aws s3 sync build/ s3://yasmines-pipeline-bucket